import {
  SiPython,
  SiCplusplus,
  SiTypescript,
  SiJavascript,
  SiC,
  SiDjango,
  SiFlask,
  SiNextdotjs,
  SiNodedotjs,
  SiReact,
  SiDocker,
  SiGit,
  SiGithubactions,
  SiLinux,
  SiPostgresql,
  SiMysql,
  SiMongodb,
  SiGooglecloud,
  SiPytorch,
  SiTensorflow,
  SiScikitlearn,
  SiKeras,
  SiPandas,
  SiNumpy,
  SiOpencv,
  SiRedis,
  SiDiscord,
  SiStreamlit,
  SiYolo,
  SiJsonwebtokens,
  SiSqlite,
  SiPrisma,
  SiElevenlabs,
  SiBetterauth,
  SiBootstrap,
  SiRaspberrypi,
  SiGooglegemini,
  SiGoogle,
  SiGoogleassistant,
  SiGooglelens,
  SiJson,
  SiSourcetree,
  SiOpenapiinitiative,
} from "@icons-pack/react-simple-icons";
import { SiOpenai, SiTwilio } from "react-icons/si";
import { FaAws, FaJava, FaMicrosoft } from "react-icons/fa6";
import { adaptIcon, type IconComp } from "./iconAdapter";
import { GroqIcon, TechDot } from "./TechIcons";

export type { IconComp };

/**
 * Centralized registry for tech names. Covers every technology that appears
 * in src/data/index.ts across skills, projects, and experience.
 * Icons are SVG brand marks from Simple Icons (@icons-pack) where available,
 * with react-icons/fa6 for brands removed from the Simple Icons library.
 */
export const TECH_ICON: Record<string, IconComp> = {
  // Languages
  Python: SiPython,
  "C++": SiCplusplus,
  Java: adaptIcon(FaJava),
  TypeScript: SiTypescript,
  JavaScript: SiJavascript,
  SQL: SiMysql,
  C: SiC,

  // Frameworks & Tools
  Django: SiDjango,
  Flask: SiFlask,
  "Next.js": SiNextdotjs,
  "Node.js": SiNodedotjs,
  React: SiReact,
  Docker: SiDocker,
  Git: SiGit,
  "GitHub Actions": SiGithubactions,
  Linux: SiLinux,

  // Databases & Cloud
  PostgreSQL: SiPostgresql,
  MySQL: SiMysql,
  MongoDB: SiMongodb,
  AWS: adaptIcon(FaAws),
  Azure: adaptIcon(FaMicrosoft),
  GCP: SiGooglecloud,

  // AI / ML & CV
  PyTorch: SiPytorch,
  TensorFlow: SiTensorflow,
  "Scikit-learn": SiScikitlearn,
  Keras: SiKeras,
  Pandas: SiPandas,
  NumPy: SiNumpy,
  OpenCV: SiOpencv,
  YOLO: SiYolo,
  YOLOv12x: SiYolo,
  OCR: SiGooglelens,
  ANPR: SiOpencv,
  Librosa: SiPython,

  // Project-specific
  "OpenAI API": adaptIcon(SiOpenai),
  Redis: SiRedis,
  Twilio: adaptIcon(SiTwilio),
  "AWS S3": adaptIcon(FaAws),
  "discord.js": SiDiscord,
  Streamlit: SiStreamlit,
  "Groq API": GroqIcon,
  "Groq Llama-4": GroqIcon,
  "REST APIs": SiOpenapiinitiative,
  JWT: SiJsonwebtokens,
  JSON: SiJson,
  "Speech Recognition": SiGoogleassistant,
  "Azure IoT Hub": adaptIcon(FaMicrosoft),
  SQLite: SiSqlite,
  "Raspberry Pi": SiRaspberrypi,
  BlueJ: adaptIcon(FaJava),
  "Bi-LSTM": SiPytorch,
  LSTM: SiPytorch,
  GRU: SiPytorch,
  TCN: SiPytorch,
  "WGAN-GP": SiPytorch,
  "Google PaLM 2": SiGooglegemini,
  "Google Model Renderer": SiGoogle,
  Bootstrap: SiBootstrap,
  AST: SiSourcetree,
  "Tree-sitter": SiSourcetree,
  Prisma: SiPrisma,
  ElevenLabs: SiElevenlabs,
  BetterAuth: SiBetterauth,
};

/** Official brand colors for hover accent. Defaults to ink-dim. */
export const BRAND_COLOR: Record<string, string> = {
  Python: "#3776AB",
  "C++": "#00599C",
  Java: "#f89820",
  TypeScript: "#3178C6",
  JavaScript: "#F7DF1E",
  SQL: "#4479A1",
  C: "#A8B9CC",
  Django: "#44B78B",
  Flask: "#000000",
  "Next.js": "#000000",
  "Node.js": "#5FA04E",
  React: "#61DAFB",
  Docker: "#2496ED",
  Git: "#F05032",
  "GitHub Actions": "#2088FF",
  Linux: "#FCC624",
  PostgreSQL: "#4169E1",
  MySQL: "#4479A1",
  MongoDB: "#47A248",
  AWS: "#FF9900",
  "AWS S3": "#FF9900",
  Azure: "#0078D4",
  "Azure IoT Hub": "#0078D4",
  GCP: "#4285F4",
  PyTorch: "#EE4C2C",
  TensorFlow: "#FF6F00",
  "Scikit-learn": "#F7931E",
  Keras: "#D00000",
  Pandas: "#150458",
  NumPy: "#4d77cf",
  OpenCV: "#5C3EE8",
  YOLO: "#00FFFF",
  YOLOv12x: "#00FFFF",
  OCR: "#4285F4",
  ANPR: "#5C3EE8",
  "OpenAI API": "#412991",
  Redis: "#FF4438",
  Twilio: "#F22F46",
  "discord.js": "#5865F2",
  Streamlit: "#FF4B4B",
  "Groq API": "#F55036",
  "Groq Llama-4": "#F55036",
  "REST APIs": "#6BA539",
  JWT: "#000000",
  JSON: "#000000",
  "Speech Recognition": "#4285F4",
  SQLite: "#003B57",
  "Raspberry Pi": "#A22846",
  BlueJ: "#f89820",
  "Bi-LSTM": "#EE4C2C",
  LSTM: "#EE4C2C",
  GRU: "#EE4C2C",
  TCN: "#EE4C2C",
  "WGAN-GP": "#EE4C2C",
  "Google PaLM 2": "#8E75B2",
  "Google Model Renderer": "#4285F4",
  Bootstrap: "#7952B3",
  AST: "#005AA5",
  "Tree-sitter": "#005AA5",
  Prisma: "#2D3748",
  ElevenLabs: "#000000",
  BetterAuth: "#000000",
  Librosa: "#3776AB",
};

export function getTechIcon(name: string): IconComp {
  return TECH_ICON[name] ?? TechDot;
}

export function getBrandColor(name: string): string {
  return BRAND_COLOR[name] ?? "#a6adbe";
}
